kind: PersistentVolumeClaim
metadata:
  name: ivia-fed-autoconf-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fed-config
spec:
  template:
    spec:
      containers:
      - name: verify-identity-access-configurator
        image: registry.access.redhat.com/ubi9/python-312
        imagePullPolicy: Never
        volumeMounts:
        - name: fedconfigvol
          mountPath: /config
        command:
        - "bash"
        - "-c"
        - |
          pip install ibmvia_autoconf

          until [ -f /config/ready ]; do
            echo "Waiting for config files to be copied across to PVC"
            sleep 3
          done
          cd /config
          echo "Starting IDP Config"
          IVIA_CONFIG_YAML=federation_idp.yaml IVIA_MGMT_BASE_URL=https://ivia-fed-idp-config:9443 python3 -m ibmvia_autoconf;
          echo "Starting SP Config" && sleep 10;
          IVIA_CONFIG_YAML=federation_sp.yaml IVIA_MGMT_BASE_URL=https://ivia-fed-sp-config:9443 python3 -m ibmvia_autoconf;
          echo "Starting IDP partner Config" && sleep 10;
          IVIA_CONFIG_YAML=federation_idp_partner.yaml IVIA_MGMT_BASE_URL=https://ivia-fed-idp-config:9443 python3 -m ibmvia_autoconf;

        envFrom:
        - secretRef:
            name: fed-env
      restartPolicy: Never
      volumes:
      - name: ivia-fed-autoconf-pvc
        persistentVolumeClaim:
          claimName: ivia-fed-autoconf-pvc
      initContainers:
      - name: config-volume-builder
        image: autoconf:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /verify_access_config
          name: fedconfigvol
        - mountPath: /tmp/fed_config
          name: fed-config
        command:
        - "bash"
        - "-c"
        - |
          cp /tmp/fed_config/*.{p12,pem,yaml} /verify_access_config/
          unzip /tmp/fed_config/mapping_rules.zip -d /verify_access_config/
  backoffLimit: 2
