### IVIA IDP Config ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isva-idp-config
  labels:
    app: isva-idp-config
spec:
  selector:
    matchLabels:
      app: isva-idp-config
  replicas: 1 
  template: 
    metadata:
      labels:
        app: isva-idp-config
    spec:
      volumes:
        - name: isva-idp-configvol
          emptyDir: {}
      containers:
        - name: isva-idp-config
          image: icr.io/isva/verify-access:10.0.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
          volumeMounts:
            - mountPath: /var/shared
              name: isva-idp-configvol
          env:
            - name: SERVICE
              value: config
            - name: CONTAINER_TIMEZONE
              value: Australia/Brisbane
            - name: CONFIG_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: url
            - name: CONFIG_SERVICE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: user
            - name: CONFIG_SERVICE_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: rw.pwd
            - name: SNAPSHOT_ID
              value: idp-published
---
apiVersion: v1
kind: Service
metadata:
  name: isva-idp-config
  labels:
    app: isva-idp-config
spec:
  ports:
    - port: 9443
      name: isva-idp-config
      protocol: TCP
  selector:
    app: isva-idp-config
  type: NodePort
---
### IVIA IDP WRP ###
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: isva-idp-webseal
  name: isva-idp-webseal
spec:
  serviceAccountName: default
  image: icr.io/isva/verify-access-wrp:10.0.6.0
  snapshotId: idp-published
  instance: default
  language: en_US.utf8
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: isva-idp-webseal
  labels:
    app: isva-idp-webseal
spec:
  ports:
    - port: 9443
      name: isva-idp-webseal
      protocol: TCP
  selector:
    app: isva-idp-webseal
  type: NodePort
---
### IVIA IDP Runtime ###
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: isva-idp-runtime
  name: isva-idp-runtime
spec:
  serviceAccountName: default
  image: icr.io/isva/verify-access-runtime:10.0.6.0
  snapshotId: idp-published
  language: en_US.utf8
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: isva-idp-runtime
  labels:
    app: isva-idp-runtime
spec:
  ports:
    - port: 9443
      name: isva-idp-runtime
      protocol: TCP
  selector:
    app: isva-idp-runtime
  type: ClusterIP
---
### IVIA SP Config ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isva-sp-config
  labels:
    app: isva-sp-config
spec:
  selector:
    matchLabels:
      app: isva-sp-config
  replicas: 1 
  template: 
    metadata:
      labels:
        app: isva-sp-config
    spec:
      volumes:
        - name: isva-sp-configvol
          emptyDir: {}
      containers:
        - name: isva-sp-config
          image: icr.io/isva/verify-access:10.0.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
          volumeMounts:
            - mountPath: /var/shared
              name: isva-sp-configvol
          env:
            - name: SERVICE
              value: config
            - name: CONTAINER_TIMEZONE
              value: Australia/Brisbane
            - name: CONFIG_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: url
            - name: CONFIG_SERVICE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: user
            - name: CONFIG_SERVICE_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: rw.pwd
            - name: SNAPSHOT_ID
              value: sp-published
---
# for external service access, see https://console.bluemix.net/docs/containers/cs_apps.html#cs_apps_public_nodeport
apiVersion: v1
kind: Service
metadata:
  name: isva-sp-config
  labels:
    app: isva-sp-config
spec:
  ports:
    - port: 9443
      name: isva-sp-config
      protocol: TCP
# make this one statically allocated and exposed to internet - comment this line out if you don't want to expose the LMI externally.
  selector:
    app: isva-sp-config
  type: ClusterIP
---
### IVIA SP WRP ###
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: isva-sp-webseal
  name: isva-sp-webseal
spec:
  serviceAccountName: default
  image: icr.io/isva/verify-access-wrp:10.0.6.0
  snapshotId: sp-published
  instance: default
  language: en_US.utf8
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: isva-sp-webseal
  labels:
    app: isva-sp-webseal
spec:
  ports:
    - port: 9443
      name: isva-sp-webseal
      protocol: TCP
  selector:
    app: isva-sp-webseal
  type: NodePort
---
### IVIA SP Runtime ###
apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: isva-sp-runtime
  name: isva-sp-runtime
spec:
  serviceAccountName: default
  image: icr.io/isva/verify-access-runtime:10.0.6.0
  snapshotId: sp-published
  language: en_US.utf8
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: isva-sp-runtime
  labels:
    app: isva-sp-runtime
spec:
  ports:
    - port: 9443
      name: isva-sp-runtime
      protocol: TCP
  selector:
    app: isva-sp-runtime
  type: ClusterIP
