name: deploy-gh-pages

# Only run this when the master branch changes
on:
  push:
    branches:
    - stable

# This job installs dependencies, builds the project's doc, and pushes it to `gh-pages`
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r dev-requirements.txt

    - name: Install hunspell
      run: |
        sudo apt-get update
        sudo apt-get install -y hunspell hunspell-en-us

    - name: Run spell check
      run: |
        cd docs && bash spellcheck.sh

    - name: Build the project
      run: |
        cd docs && bash generate_schema_html.sh && cd ..
        sphinx-build docs html
        python -m build

    - name: Publish module
      run: |
        python -m build
        twine upload --verbose dist/* -u $PYPI_API_USER -p $PYPI_API_KEY
      env:
        PYPI_API_USER: ${{ secrets.PYPI_API_USER }}
        PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
      if: github.ref == 'refs/heads/stable'

    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: html/
        force_orphan: true
      if: github.ref == 'refs/heads/stable'
